name = "GuiSDE"
uuid = "aad8d45a-76ef-4b4c-a224-6d74feee4af3"
authors = ["mschauer <moritzschauer@web.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
